services:
  api:
    build:
      context: .
      args:
        - DEV=true
    ports:
       - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ENV=dev
      - DB_HOST=osc-dev-db
      - DB_NAME=devdatabase
      - DB_USER=devuser
      - DB_PASS=devpass
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - S3_STORAGE_BACKEND=0
      - CREATE_SUPERUSER=1
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: osc-dev-db
    volumes:
      - postgres-osc-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdatabase
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
  
  coverage:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./app/htmlcov:/usr/share/nginx/html

volumes:
  postgres-osc-dev:



